In [4]:
#task1
import numpy as np

a = np.empty((2, 2))
print(a)

[[3.43578597e-315 0.00000000e+000]
 [5.77154444e-317 5.77207013e-317]]


In [5]:
#task1
import numpy as np

a = np.ones((4, 2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
#task1
import numpy as np

a = np.full((3, 3), 7)
print(a)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [7]:
#task1
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5 , 6]])
array = np.zeros_like(a)
print(array)

[[0 0 0]
 [0 0 0]]


In [8]:
#task1
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5 , 6]])
array = np.ones_like(a)
print(array)

[[1 1 1]
 [1 1 1]]


In [9]:
#task1
import numpy as np
new_list = [1,2,3,4]
array=np.array(new_list)
print(array)

[1 2 3 4]


In [ ]:
#task2
import numpy as np
array = np.arange(10, 50)
print(array)

In [10]:
#task2
import numpy as np
array = np.arange(0,9).reshape(3, 3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#task2
import numpy as np
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#task2
import numpy as np
a = np.random.random(30)
mean_value = a.mean()
print("Array:", a)
print("Mean:", mean_value)

Array: [0.76409326 0.81239686 0.60979782 0.18781286 0.99327452 0.68441694
 0.1877985  0.09576679 0.04651055 0.71619615 0.78732499 0.04522283
 0.13646143 0.76626317 0.26726742 0.70667848 0.41229374 0.57410944
 0.10390365 0.68002255 0.23872115 0.47888305 0.12382611 0.99853165
 0.97984652 0.55921145 0.06909672 0.09180849 0.27167486 0.26063367]
Mean: 0.45499485433557835


In [17]:
#task2
import numpy as np
a = np.random.random((10, 10))
min_value = a.min()
max_value = a.max()
print("Array: ", a)
print("Minimum value: ", min_value)
print("Maximum value: ", max_value)

Array:  [[0.0796241  0.42310215 0.86649392 0.93116765 0.26939259 0.82149167
  0.49084963 0.42943271 0.43216605 0.95682181]
 [0.57582763 0.022425   0.86073225 0.58839855 0.63440958 0.97711413
  0.27242219 0.17404069 0.01466264 0.75703081]
 [0.88168557 0.94091051 0.49396448 0.56631948 0.77822599 0.44034047
  0.5176118  0.45128258 0.66467111 0.50092438]
 [0.05318912 0.97062967 0.97599177 0.6789331  0.06852293 0.6011997
  0.60981672 0.49377567 0.34401858 0.15571298]
 [0.08475988 0.24087101 0.19594068 0.73335284 0.0570985  0.02863253
  0.07299499 0.75317106 0.4348009  0.01244193]
 [0.69609939 0.87281896 0.06720923 0.06709056 0.61472434 0.60616208
  0.76684467 0.34701735 0.1063505  0.07400633]
 [0.47078317 0.80266117 0.7825195  0.83273122 0.11369897 0.15324401
  0.56868603 0.32790233 0.85804271 0.45382349]
 [0.80635459 0.01552131 0.62088174 0.23402557 0.44348043 0.27820449
  0.39006219 0.94422229 0.22302219 0.19359914]
 [0.43794059 0.08742804 0.79776742 0.39818384 0.65064312 0.28561285
  0.8

In [20]:
#task2
import numpy as np
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [22]:
#task2
import numpy as np
arr = [1,2,0,0,4,0]
rev_array=arr[::-1]
print(rev_array)

[0, 4, 0, 0, 2, 1]


In [23]:
#task2
import numpy as np
arr = np.ones((4, 4))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [24]:
#task2
import numpy as np
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [2]:
from typing_extensions import MutableMapping
#task3
import numpy as np
x = np.array([[1, 2],
              [3, 5]])
y = np.array([[5, 6],
              [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
#1
add = x + y
print(add)
#2
sub= x - y
print(sub)
#3
multi = x * 7
print(multi)
#4
square = y ** 2
print(square)
#5
dot_1 = np.dot(v, w)
print(dot_1)
dot_2 = np.dot(x, v)
print(dot_2)
dot_3 = np.dot(x, y)
print(dot_3)
#6
concat_xy_rows = np.concatenate((x, y))
print(concat_xy_rows)
concat_vw_cols = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)))
print(concat_vw_cols)
#7
concat_xv=np.concatenate((x, v))
print(concat_xv)
#NumPy cannot concatenate a 2D array with a 1D array unless dimensions match.
#To concatenate successfully, v must be reshaped.

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 7 14]
 [21 35]]
[[25 36]
 [49 64]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9]
 [10]
 [11]
 [12]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [7]:
#task4
import numpy as np
A = np.array([[3, 4],
              [7, 8]])
B = np.array([[5, 3],
              [2, 1]])
#1
A_inv = np.linalg.inv(A)
I=A@A_inv
print(I)
#2
AB = A @ B
BA = B @ A
print("AB ", AB)
print("BA", BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))
#3
left = (A @ B).T
right = B.T @ A.T
print("Are they equal?", np.array_equal(left, right))
#Inverse method
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])

B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = A_inv @ B
print("Result", X)
#

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB  [[23 13]
 [51 29]]
BA [[36 44]
 [13 16]]
Are AB and BA equal? False
Are they equal? True
Result [ 2.  1. -2.]
